theme: jekyll-theme-minimal
title: Smart Health Assistant
description: Quick health assessment tool - Get instant insights about your health status
baseurl: "/smart-health-assistant"
url: "https://aaryapatel09.github.io" 